cronwrap - shellcheck

diff --git a/cronwrap b/cronwrap
--- a/cronwrap
+++ b/cronwrap
@@ -38,11 +38,15 @@
 usage() {
    echo 'usage: cronwrap [ options ] name interval command' >&2
    echo >&2
+   # shellcheck disable=2016
    echo '  -d cronwrap_log_dir   (or set CRONWRAP_LOG_DIR)   default: /var/log/cronwrap/${name}' >&2
+   # shellcheck disable=2016
    echo '  -l cronwrap_lock_dir  (or set CRONWRAP_LOCK_DIR)  default: /var/log/cronwrap/${name}' >&2
+   # shellcheck disable=2016
    echo '  -n cronwrap_lock_name (or set CRONWRAP_LOCK_NAME) default: ${name}'                   >&2
    echo '  -q                    (or set CRONWRAP_QUIET_LOCK) record locked jobs with status OK' >&2
    echo >&2
+   # shellcheck disable=2016
    echo 'lockfile is ${cronwrap_lock_dir}/${cronwrap_lock_name}.lock'                            >&2
    exit 1
  }
@@ -60,7 +64,7 @@ shift $((OPTIND -1))
 
 NAME=$1 ; shift
 INT=$1  ; shift
-CMD=$@
+CMD="$*"
 
 fail() {
   echo "cronwrap: FATAL $*"
@@ -85,105 +89,106 @@ PATH=${CRONWRAP_PATH:-${PATH}}
 QUIET_LOCK=${CRONWRAP_QUIET_LOCK:-}
 
 STAMP=$( date '+%Y%m%d-%H%M%S' )
-TIME=$( date '+%s' )
 
 LOCKRUN=${CRONWRAP_LOCKRUN:-/usr/local/bin/lockrun}
-[ -x ${LOCKRUN} ] || fail "can't find lockrun at ${LOCKRUN}"
+[ -x "${LOCKRUN}" ] || fail "can't find lockrun at ${LOCKRUN}"
 
-mkdir -p ${LOG_DIR}    || fail "couldn't create ${LOG_DIR}"
-mkdir -p ${LOCK_DIR}   || fail "couldn't create ${LOCK_DIR}"
-mkdir -p ${STATUS_DIR} || fail "couldn't create ${STATUS_DIR}"
+mkdir -p "${LOG_DIR}"    || fail "couldn't create ${LOG_DIR}"
+mkdir -p "${LOCK_DIR}"   || fail "couldn't create ${LOCK_DIR}"
+mkdir -p "${STATUS_DIR}" || fail "couldn't create ${STATUS_DIR}"
 LOG=${CRON_DIR}/${STAMP}.log
 TMP=${CRON_DIR}/$$.log # feeble, but gives us route back to the running job
 
-touch ${STATUS_DIR}/job_ok
-touch ${STATUS_DIR}/job_fail
-touch ${STATUS_DIR}/lock_fail
+touch "${STATUS_DIR}/job_ok"
+touch "${STATUS_DIR}/job_fail"
+touch "${STATUS_DIR}/lock_fail"
 
-echo ${STAMP} > ${STATUS_DIR}/last_attempt
-echo ${INT}   > ${STATUS_DIR}/interval
+echo "${STAMP}" > "${STATUS_DIR}/last_attempt"
+echo "${INT}"   > "${STATUS_DIR}/interval"
 
-date > ${TMP}
-echo "host: ${HOST}"    >> ${TMP}
-echo "name: ${NAME}"    >> ${TMP}
-echo "interval: ${INT}" >> ${TMP}
-echo "command: ${CMD}"  >> ${TMP}
-echo "wrapped: ${LOCKRUN} --lockfile ${LOCK} --verbose -- $@" >> ${TMP}
+# shellcheck disable=2129
+date > "${TMP}"
+# shellcheck disable=2129
+echo "host: ${HOST}"    >> "${TMP}"
+echo "name: ${NAME}"    >> "${TMP}"
+echo "interval: ${INT}" >> "${TMP}"
+echo "command: ${CMD}"  >> "${TMP}"
+echo "wrapped: ${LOCKRUN} --lockfile ${LOCK} --verbose -- $*" >> "${TMP}"
 
-echo >> ${TMP}
+echo >> "${TMP}"
 
-${LOCKRUN} --lockfile ${LOCK} --verbose -- "$@" >> ${TMP} 2>&1
+${LOCKRUN} --lockfile "${LOCK}" --verbose -- "$@" >> "${TMP}" 2>&1
 EXIT=$?
 
-echo >> ${TMP}
+echo >> "${TMP}"
 
-if [ ${EXIT} -gt 0 ] && grep -q 'run is locked' ${TMP} ; then
+if [ ${EXIT} -gt 0 ] && grep -q 'run is locked' "${TMP}" ; then
   # run was locked
 
   if [ -z "${QUIET_LOCK}" ] ; then
-    echo "failed: lockrun indicated earlier process running" >> ${TMP}
-    mv ${TMP} ${LOG}
+    echo "failed: lockrun indicated earlier process running" >> "${TMP}"
+    mv "${TMP}" "${LOG}"
 
-    ln -nsf ${LOG} ${CRON_DIR}/last_run
-    ln -nsf ${LOG} ${CRON_DIR}/last_lock_fail
-    rm -f ${STATUS_DIR}/OK
-    rm -f ${STATUS_DIR}/FAIL
-    echo ${STAMP} >  ${STATUS_DIR}/LOCK
-    echo ${STAMP} >> ${STATUS_DIR}/lock_fail
+    ln -nsf "${LOG}" "${CRON_DIR}/last_run"
+    ln -nsf "${LOG}" "${CRON_DIR}/last_lock_fail"
+    rm -f "${STATUS_DIR}/OK"
+    rm -f "${STATUS_DIR}/FAIL"
+    echo "${STAMP}" >  "${STATUS_DIR}/LOCK"
+    echo "${STAMP}" >> "${STATUS_DIR}/lock_fail"
   else
-    echo "failed: lockrun indicated earlier process running (quiet lock mode)" >> ${TMP}
-    mv ${TMP} ${LOG}
+    echo "failed: lockrun indicated earlier process running (quiet lock mode)" >> "${TMP}"
+    mv "${TMP}" "${LOG}"
 
     # in quiet mode we link the log as lock_fail and touch the lock_fail marker
     # but set the overall status as OK
-    ln -nsf ${LOG} ${CRON_DIR}/last_run
-    ln -nsf ${LOG} ${CRON_DIR}/last_lock_fail
-    rm -f ${STATUS_DIR}/LOCK
-    rm -f ${STATUS_DIR}/FAIL
-    echo ${STAMP} >  ${STATUS_DIR}/OK
-    echo ${STAMP} >> ${STATUS_DIR}/lock_fail
+    ln -nsf "${LOG}" "${CRON_DIR}/last_run"
+    ln -nsf "${LOG}" "${CRON_DIR}/last_lock_fail"
+    rm -f "${STATUS_DIR}/LOCK"
+    rm -f "${STATUS_DIR}/FAIL"
+    echo "${STAMP}" >  "${STATUS_DIR}/OK"
+    echo "${STAMP}" >> "${STATUS_DIR}/lock_fail"
   fi
 
   if [ -n "${DEBUG}" ] ; then
     echo lock_fail
     echo
-    cat ${LOG}
+    cat "${LOG}"
   fi
   exit 1
 fi
 
-if [ ${EXIT} -gt 0 ] ; then
+if [ "${EXIT}" -gt 0 ] ; then
   # command ran, but errored
-  echo "failed: command exited non-zero" >> ${TMP}
-  mv ${TMP} ${LOG}
-  ln -nsf ${LOG} ${CRON_DIR}/last_run
-  ln -nsf ${LOG} ${CRON_DIR}/last_job_fail
-  rm -f ${STATUS_DIR}/OK
-  rm -f ${STATUS_DIR}/LOCK
-  echo ${STAMP} >  ${STATUS_DIR}/FAIL
-  echo ${STAMP} >> ${STATUS_DIR}/job_fail
+  echo "failed: command exited non-zero" >> "${TMP}"
+  mv "${TMP}" "${LOG}"
+  ln -nsf "${LOG}" "${CRON_DIR}/last_run"
+  ln -nsf "${LOG}" "${CRON_DIR}/last_job_fail"
+  rm -f "${STATUS_DIR}/OK"
+  rm -f "${STATUS_DIR}/LOCK"
+  echo "${STAMP}" >  "${STATUS_DIR}/FAIL"
+  echo "${STAMP}" >> "${STATUS_DIR}/job_fail"
 
   if [ -n "${DEBUG}" ] ; then
     echo job_fail
     echo
-    cat ${LOG}
+    cat "${LOG}"
   fi
   exit 2
 fi
 
-echo "success: job exited ok" >> ${TMP}
-mv ${TMP} ${LOG}
-ln -nsf ${LOG} ${CRON_DIR}/last_run
-ln -nsf ${LOG} ${CRON_DIR}/last_job_ok
-rm -f ${STATUS_DIR}/FAIL
-rm -f ${STATUS_DIR}/LOCK
-echo ${STAMP} >  ${STATUS_DIR}/OK
-echo ${STAMP} >> ${STATUS_DIR}/job_ok
+echo "success: job exited ok" >> "${TMP}"
+mv "${TMP}" "${LOG}"
+ln -nsf "${LOG}" "${CRON_DIR}/last_run"
+ln -nsf "${LOG}" "${CRON_DIR}/last_job_ok"
+rm -f "${STATUS_DIR}/FAIL"
+rm -f "${STATUS_DIR}/LOCK"
+echo "${STAMP}" >  "${STATUS_DIR}/OK"
+echo "${STAMP}" >> "${STATUS_DIR}/job_ok"
 
 if [ -n "${DEBUG}" ] ; then
   echo job_ok
   echo
-  cat ${LOG}
+  cat "${LOG}"
 fi
 
 exit 0
