cronwrap - add "quiet lock" mode
This lets overlapping jobs fail quietly:

* they're still prevented from running
* they still stop `lock_fail` marker and link `last_lock_fail` log
* they drop `status/OK` instead of `status/LOCK` marker

The upshot is the `check_cronwrap` doesn't consider the locked-out as
failed, so monitoring ignores it.

diff --git a/cronwrap b/cronwrap
--- a/cronwrap
+++ b/cronwrap
@@ -41,16 +41,18 @@ usage() {
    echo '  -d cronwrap_log_dir   (or set CRONWRAP_LOG_DIR)   default: /var/log/cronwrap/${name}' >&2
    echo '  -l cronwrap_lock_dir  (or set CRONWRAP_LOCK_DIR)  default: /var/log/cronwrap/${name}' >&2
    echo '  -n cronwrap_lock_name (or set CRONWRAP_LOCK_NAME) default: ${name}'                   >&2
+   echo '  -q                    (or set CRONWRAP_QUIET_LOCK) record locked jobs with status OK' >&2
    echo >&2
    echo 'lockfile is ${cronwrap_lock_dir}/${cronwrap_lock_name}.lock'                            >&2
    exit 1
  }
 
-while getopts ":d:l:n:" opt ; do
+while getopts ":d:l:n:q" opt ; do
   case ${opt} in
-    d)  CRONWRAP_LOG_DIR=${OPTARG}  ;;
-    l)  CRONWRAP_LOCK_DIR=${OPTARG} ;;
+    d)  CRONWRAP_LOG_DIR=${OPTARG}   ;;
+    l)  CRONWRAP_LOCK_DIR=${OPTARG}  ;;
     n)  CRONWRAP_LOCK_NAME=${OPTARG} ;;
+    q)  CRONWRAP_QUIET_LOCK=1        ;;
     \?) usage ;;
   esac
 done
@@ -79,6 +81,8 @@ LOCK_NAME=${CRONWRAP_LOCK_NAME:-${NAME}}
 LOCK=${LOCK_DIR}/${LOCK_NAME}.lock
 HOST=$( uname -n )
 PATH=${CRONWRAP_PATH:-${PATH}}
+
+QUIET_LOCK=${CRONWRAP_QUIET_LOCK:-}
 
 STAMP=$( date '+%Y%m%d-%H%M%S' )
 TIME=$( date '+%s' )
@@ -115,14 +119,30 @@ echo >> ${TMP}
 
 if [ ${EXIT} -gt 0 ] && grep -q 'run is locked' ${TMP} ; then
   # run was locked
-  echo "failed: lockrun indicated earlier process running" >> ${TMP}
-  mv ${TMP} ${LOG}
-  ln -nsf ${LOG} ${CRON_DIR}/last_run
-  ln -nsf ${LOG} ${CRON_DIR}/last_lock_fail
-  rm -f ${STATUS_DIR}/OK
-  rm -f ${STATUS_DIR}/FAIL
-  echo ${STAMP} >  ${STATUS_DIR}/LOCK
-  echo ${STAMP} >> ${STATUS_DIR}/lock_fail
+
+  if [ -z "${QUIET_LOCK}" ] ; then
+    echo "failed: lockrun indicated earlier process running" >> ${TMP}
+    mv ${TMP} ${LOG}
+
+    ln -nsf ${LOG} ${CRON_DIR}/last_run
+    ln -nsf ${LOG} ${CRON_DIR}/last_lock_fail
+    rm -f ${STATUS_DIR}/OK
+    rm -f ${STATUS_DIR}/FAIL
+    echo ${STAMP} >  ${STATUS_DIR}/LOCK
+    echo ${STAMP} >> ${STATUS_DIR}/lock_fail
+  else
+    echo "failed: lockrun indicated earlier process running (quiet lock mode)" >> ${TMP}
+    mv ${TMP} ${LOG}
+
+    # in quiet mode we link the log as lock_fail and touch the lock_fail marker
+    # but set the overall status as OK
+    ln -nsf ${LOG} ${CRON_DIR}/last_run
+    ln -nsf ${LOG} ${CRON_DIR}/last_lock_fail
+    rm -f ${STATUS_DIR}/LOCK
+    rm -f ${STATUS_DIR}/FAIL
+    echo ${STAMP} >  ${STATUS_DIR}/OK
+    echo ${STAMP} >> ${STATUS_DIR}/lock_fail
+  fi
 
   if [ -n "${DEBUG}" ] ; then
     echo lock_fail
@@ -159,6 +179,7 @@ rm -f ${STATUS_DIR}/FAIL
 rm -f ${STATUS_DIR}/LOCK
 echo ${STAMP} >  ${STATUS_DIR}/OK
 echo ${STAMP} >> ${STATUS_DIR}/job_ok
+
 if [ -n "${DEBUG}" ] ; then
   echo job_ok
   echo
